apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ include "tofu-controller-app.fullname" . }}-git
  namespace: {{ .Release.Namespace }}
spec:
  interval: 1m
  url: {{ .Values.terraform.git.url }}
  subPath: {{ .Values.terraform.git.subPath }}
  ref:
    branch: {{ .Values.terraform.git.branch }}