apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tofu-controller-app.fullname" . }}-db-creds
type: Opaque
stringData:
  DB_NAME: "{{ .Values.db.name }}"
  DB_USER: "{{ .Values.db.user }}"
  DB_PASSWORD: "{{ .Values.db.password }}"
