apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: flux-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID:     "{{ .Values.aws.accessKeyId }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.aws.secretAccessKey }}"
  AWS_REGION:            "{{ .Values.aws.region }}"