apiVersion: v1
kind: Service
metadata:
  name: {{ include "tofu-controller-app.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "tofu-controller-app.name" . }}
