{{- if .Values.terraform.enabled }}
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: {{ include "tofu-controller-app.fullname" . }}-rds
  namespace: {{ .Release.Namespace }}
spec:
  sourceRef:
    kind: GitRepository
    name: {{ include "tofu-controller-app.fullname" . }}-git
    namespace: {{ .Release.Namespace }}
  path: {{ .Values.terraform.git.path }}
  interval: 1m

  approvePlan: auto

  vars:
    - name: aws_region
      value: "{{ .Values.aws.region }}"
    - name: vpc_cidr
      value: "{{ .Values.vpc.cidr }}"
    - name: private_subnets
      value:
{{ toYaml .Values.privateSubnets | indent 8 }}
    - name: db_instance_class
      value: "{{ .Values.db.instanceClass | default "db.t3.micro" }}"
    - name: db_allocated_storage
      value: "{{ .Values.db.allocatedStorage | default 20 }}"
    - name: db_name
      value: "{{ .Values.db.name }}"
    - name: db_username
      value: "{{ .Values.db.user }}"
    - name: db_password
      value: "{{ .Values.db.password }}"

  # Capture Terraform outputs (e.g. db_endpoint) into a k8s Secret
  writeOutputsToSecret:
    name: rds-output

  # Mount the AWS creds secret into the runner Pod
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-credentials
{{- end }}